// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaJNc-3_2LaVD4A2XBxsdBf_w4k5VtytI',
    appId: '1:850514984483:web:1e4dc68c38e15e97203b96',
    messagingSenderId: '850514984483',
    projectId: 'peminjaman-alat-lab-5f524',
    authDomain: 'peminjaman-alat-lab-5f524.firebaseapp.com',
    storageBucket: 'peminjaman-alat-lab-5f524.firebasestorage.app',
    measurementId: 'G-7K4TNHD1N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfo3jhkXOzYLBwhCDljIEUXuTWJBcSa7o',
    appId: '1:850514984483:android:7829c36b8fdf07cd203b96',
    messagingSenderId: '850514984483',
    projectId: 'peminjaman-alat-lab-5f524',
    storageBucket: 'peminjaman-alat-lab-5f524.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfTSELJwpQhNovrmv2Ktms5-1kf3m3xyQ',
    appId: '1:850514984483:ios:bdd97853ac2f5b10203b96',
    messagingSenderId: '850514984483',
    projectId: 'peminjaman-alat-lab-5f524',
    storageBucket: 'peminjaman-alat-lab-5f524.firebasestorage.app',
    iosBundleId: 'com.example.pblPeminjamanalatlab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfTSELJwpQhNovrmv2Ktms5-1kf3m3xyQ',
    appId: '1:850514984483:ios:bdd97853ac2f5b10203b96',
    messagingSenderId: '850514984483',
    projectId: 'peminjaman-alat-lab-5f524',
    storageBucket: 'peminjaman-alat-lab-5f524.firebasestorage.app',
    iosBundleId: 'com.example.pblPeminjamanalatlab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaJNc-3_2LaVD4A2XBxsdBf_w4k5VtytI',
    appId: '1:850514984483:web:8931fe979aa30c89203b96',
    messagingSenderId: '850514984483',
    projectId: 'peminjaman-alat-lab-5f524',
    authDomain: 'peminjaman-alat-lab-5f524.firebaseapp.com',
    storageBucket: 'peminjaman-alat-lab-5f524.firebasestorage.app',
    measurementId: 'G-LLHQ6HW297',
  );
}
